dbal_manager:
    Incubatrix\DbalManager\MysqlDriver:
        class: Incubatrix\DbalManager\MysqlDriver

    Incubatrix\DbalManager\DbalManager:
        class: Incubatrix\DbalManager\DbalManager
        arguments:
            $driver: '@Incubatrix\DbalManager\MysqlDriver'
